{{- if .Values.configMapData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-conf" (include "llince.fullname" .) }}
data:
{{- range $key, $value := .Values.configMapData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
