---
# Source: llince/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: generatebackend-v1
  labels:
    app: generatebackend-v1
    helm.sh/chart: llince-0.1.0
    app.kubernetes.io/name: llince
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: generatebackend-v1
